version: '3.0'
services:
  app:
    image: tuchfarber/photodb_frontend:prod
    volumes:
      - ./web/:/web/
    entrypoint: bash -c "npm run build && mkdir /web/dist && cp -R /code/dist/ /web/dist/ && cp /code/index.html /web/index.html"
